### ISSUE TITLE
How to use this extension, how to configure folders on windows 10

### ISSUE THREAD

**Issue by matheusgrodrigues** [rahulshekhawat/blender-elu-ani-importer#1]
Good afternoon, I am desperate, I tried all the ways to configure the path of folders in windows 10 and it is not exporting, it does not load the .elu in blender and nothing, the blender even locks the elu file drag for it, it could help me to to set up.

**main.py**

`# SET SourceDir TO datadump/data FOLDER. DON'T LEAVE IT NONE
SourceDir = r'D:\GameDev\asset_src'
`

`# SET DestinationDir TO WHERE YOU WOULD LIKE TO EXPORT FBX FILES. DON'T LEAVE IT NONE
DestinationDir = r'D:\GameDev\asset_dest'
`

**filedatatypes.py**

 `if SourceDir is None: 

         self.SourceDir = r'D:\GameDev\asset_src' 

         else:> 

         self.SourceDir = SourceDir 

         if DestinationDir is None:

         self.DestinationDir = r'D:\GameDev\asset_dest'

          else:

          self.DestinationDir = DestinationDir`

# Source directories
        self.MonstersDirPath = self.SourceDir + r'\Model\Monster'
        self.StaticsDirPath = self.SourceDir + r'\Model\MapObject'
        self.FemaleDirPath = self.SourceDir + r'\Model\Player\hf'
        self.MaleDirPath = self.SourceDir + r'\Model\Player\hm'
        self.RidesDirPath = self.SourceDir + r'\Model\Ride'
        self.SkiesDirPath = self.SourceDir + r'\Model\Sky'
        self.WeaponsDirPath = self.SourceDir + r'\Model\weapons'
        self.NPCDirPath = self.SourceDir + r'\Model\NPC'
        self.SFXDirPath = self.SourceDir + r'\SFX'`

I created this folder structure manually within GameDev / asset_src and asset_dest.

in BlenderEluLoader.blend, I give a Runscript and apparently executes, I drag a .elu into the viewport of the blender and nothing happens, only in the console appears "drop file" file path and dragged file ", when clicking on Runscript it is in a loop infinite and the blender crashes.

I need urgent help because I need to export some .elu files to fbx.

If you can make a video configuring I thank you very much or help me with a tutorial. THANK YOU.

"GOOGLE TRADUTOR XD"

**Comment by rahulshekhawat** [comment]
This plugin only works with the versions of .elu and .ani files that were used in RaiderZ files. This will NOT work with GunZ files. Someone contacted me about that earlier as well and I checked, the GunZ file formats are older than the ones used in RaiderZ.

When using it with RaiderZ however, the directory structure is exactly as described on README.md. Nothing needs to be changed except pointing SourceDir to the folder path of `datadump/data` directory. You do NOT need to edit filedatatypes.py. This has worked for me, as well as anyone else who has used it used it to extract RaiderZ's .elu/.ani models.

I checked your GitHub and I'm guessing you need this to extract GunZ files? These scripts won't work with GunZ files.

**Comment by matheusgrodrigues** [comment]
OK. thank you very much for taking my doubts.
